Repository sufst/vcu, pull requests merged in 2022-03, with the labels that each got.

#49 Throttle input test bench / system config header
  .gitignore
  PID.py
  embedded/SUFST/Inc/Test/testbench.h
  embedded/SUFST/Inc/Test/throttle_testbench_data.h
  embedded/SUFST/Inc/config.h
  embedded/SUFST/Src/Test/testbench.c
  embedded/SUFST/Src/Test/throttle_testbench_data.c
  embedded/SUFST/Src/can_thread.c
  embedded/SUFST/Src/sensor_thread.c
  scripts/csv/lapsim_flying_lap.csv
  scripts/csv/lapsim_standing_start.csv
  scripts/testbench_generate.py
Labels: feature

#60 Fault state outline
  embedded/.cproject
  embedded/Core/Inc/main.h
  embedded/Core/Inc/rtc.h
  embedded/Core/Inc/stm32h7xx_hal_conf.h
  embedded/Core/Src/app_threadx.c
  embedded/Core/Src/gpio.c
  embedded/Core/Src/main.c
  embedded/Core/Src/rtc.c
  embedded/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_rtc.h
  embedded/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_rtc_ex.h
  embedded/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc.c
  embedded/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc_ex.c
  embedded/SUFST/Inc/Test/testbench.h
  embedded/SUFST/Inc/can_thread.h
  embedded/SUFST/Inc/config.h
  embedded/SUFST/Inc/control_thread.h
  embedded/SUFST/Inc/fault_state_thread.h
  embedded/SUFST/Inc/sensor_thread.h
  embedded/SUFST/Src/Test/testbench.c
  embedded/SUFST/Src/can_thread.c
  embedded/SUFST/Src/config_rules.c
  embedded/SUFST/Src/control_thread.c
  embedded/SUFST/Src/fault_state_thread.c
  embedded/SUFST/Src/ready_to_drive.c
  embedded/SUFST/Src/sensor_thread.c
  embedded/VCU.ioc
Labels: feature

#64 Add some useful links to the README
  .github/README.md
  README.md
  docs/markdown/Software Outline.md
Labels: documentation

#71 Add return codes, command struct
  embedded/SUFST/Inc/can_types.h
  embedded/SUFST/Inc/pm100.h
  embedded/SUFST/Src/can_types.c
  embedded/SUFST/Src/pm100.c
Labels: feature

#70 RTC delay functions
  embedded/Core/Src/app_threadx.c
  embedded/Core/Src/main.c
  embedded/SUFST/Inc/config.h
  embedded/SUFST/Inc/rtc_time.h
  embedded/SUFST/Src/can_thread.c
  embedded/SUFST/Src/pm100.c
  embedded/SUFST/Src/ready_to_drive.c
  embedded/SUFST/Src/rtc_time.c
Labels: bug, improvement

#72 Inverter code integration and cleanup
  embedded/Core/Src/app_threadx.c
  embedded/Core/Src/main.c
  embedded/SUFST/Inc/can_types.h
  embedded/SUFST/Inc/config.h
  embedded/SUFST/Inc/pm100.h
  embedded/SUFST/Inc/rtc_time.h
  embedded/SUFST/Src/can_thread.c
  embedded/SUFST/Src/can_types.c
  embedded/SUFST/Src/pm100.c
  embedded/SUFST/Src/ready_to_drive.c
  embedded/SUFST/Src/rtc_time.c
Labels: improvement, feature
